### ISSUE TITLE
RBP prediction with local pfam database?

### ISSUE THREAD

**Issue by xflicsu** [gianlucacorrado/RNAcommender#6]
Hello again!
     I try to use RNAcommender to predict RBP-RNA interaction.
     But rbpfeatures.py cost lots of time.
     So, any method to accelerate this step with local pfam database?

**Comment by gianlucacorrado** [comment]
How many RBPs do you have in your dataset?

There is no easy way of using a local PFAM database. But if I remember correctly the REST interface of PFAM was replying in 3-5 seconds for each request. 5 seconds * 10000 RBPs (random big number) is around 14h of computation. 

If is can be a one-off computation you can schedule it over-night or over the weekend.

Cheers
